In [1]:
#MakeMore -  Step by Step Language Modelling (Character Level)

In [2]:
words = open('names.txt').read().splitlines() #reading text file and split data and store as list

In [3]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [4]:
len(words)

32033

In [5]:
min(len(w) for w in words)

2

In [6]:
max(len(w) for w  in words)

15

In [7]:
#Building Bigram i.e always work with 2 characters at a time...i.e given a character, will predict next character

In [8]:
for w in words[:1]: #lets examine 1st word i.e emma in the list
    for ch1, ch2 in zip(w, w[1:]): #zipping each word with word without 1st letter to get 2 consequtive characters
        print(ch1, ch2)

e m
m m
m a


In [9]:
#Notice how 2 consecutive characters were extracted 

In [10]:
w

'emma'

In [11]:
w[1:]

'mma'

In [12]:
#when any one of word size dont match, it will stop....

In [13]:
#lets add special char to notice start and end of words

In [14]:
for w in words[:1]: #lets examine 1st word i.e emma in the list
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(w, w[1:]): #zipping each word with word without 1st letter to get 2 consequtive characters
        print(ch1, ch2)

e m
m m
m a


In [15]:
list(w)

['e', 'm', 'm', 'a']

In [16]:
#notice list of w, extracted each characters in the word as individual elements

In [17]:
#therefore we will iterate from chs instead of w's
for w in words[:1]: #lets examine 1st word i.e emma in the list
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]): #zipping each word with word without 1st letter to get 2 consequtive characters
        print(ch1, ch2)

<S> e
e m
m m
m a
a <E>


In [18]:
for w in words[:2]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]): #zipping each word with word without 1st letter to get 2 consequtive characters
        print(ch1, ch2)

<S> e
e m
m m
m a
a <E>
<S> o
o l
l i
i v
v i
i a
a <E>


In [19]:
#notice how we identify start and end of each words using special symbols added

In [20]:
#basically to identify which char comes next for given char, we find statistics of finding frequency

In [21]:
#therefor we create a dictionary to keep counter for each of these bigrams
b = {}
for w in words[:2]: #lets examine 1st word i.e emma in the list
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]): #zipping each word with word without 1st letter to get 2 consequtive characters
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1# check if the bigram exists in dict, if not return 0; if present inc counter by 1
        print(ch1, ch2)

<S> e
e m
m m
m a
a <E>
<S> o
o l
l i
i v
v i
i a
a <E>


In [22]:
b

{('<S>', 'e'): 1,
 ('e', 'm'): 1,
 ('m', 'm'): 1,
 ('m', 'a'): 1,
 ('a', '<E>'): 2,
 ('<S>', 'o'): 1,
 ('o', 'l'): 1,
 ('l', 'i'): 1,
 ('i', 'v'): 1,
 ('v', 'i'): 1,
 ('i', 'a'): 1}

In [23]:
#lets do for all the words
b = {}
for w in words: #lets examine 1st word i.e emma in the list
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]): #zipping each word with word without 1st letter to get 2 consequtive characters
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1# check if the bigram exists in dict, if not return 0; if present inc counter by 1

In [24]:
b

{('<S>', 'e'): 1531,
 ('e', 'm'): 769,
 ('m', 'm'): 168,
 ('m', 'a'): 2590,
 ('a', '<E>'): 6640,
 ('<S>', 'o'): 394,
 ('o', 'l'): 619,
 ('l', 'i'): 2480,
 ('i', 'v'): 269,
 ('v', 'i'): 911,
 ('i', 'a'): 2445,
 ('<S>', 'a'): 4410,
 ('a', 'v'): 834,
 ('v', 'a'): 642,
 ('<S>', 'i'): 591,
 ('i', 's'): 1316,
 ('s', 'a'): 1201,
 ('a', 'b'): 541,
 ('b', 'e'): 655,
 ('e', 'l'): 3248,
 ('l', 'l'): 1345,
 ('l', 'a'): 2623,
 ('<S>', 's'): 2055,
 ('s', 'o'): 531,
 ('o', 'p'): 95,
 ('p', 'h'): 204,
 ('h', 'i'): 729,
 ('<S>', 'c'): 1542,
 ('c', 'h'): 664,
 ('h', 'a'): 2244,
 ('a', 'r'): 3264,
 ('r', 'l'): 413,
 ('l', 'o'): 692,
 ('o', 't'): 118,
 ('t', 't'): 374,
 ('t', 'e'): 716,
 ('e', '<E>'): 3983,
 ('<S>', 'm'): 2538,
 ('m', 'i'): 1256,
 ('a', 'm'): 1634,
 ('m', 'e'): 818,
 ('<S>', 'h'): 874,
 ('r', 'p'): 14,
 ('p', 'e'): 197,
 ('e', 'r'): 1958,
 ('r', '<E>'): 1377,
 ('e', 'v'): 463,
 ('v', 'e'): 568,
 ('l', 'y'): 1588,
 ('y', 'n'): 1826,
 ('n', '<E>'): 6763,
 ('b', 'i'): 217,
 ('i', 'g'): 428,


In [25]:
b.items()

dict_items([(('<S>', 'e'), 1531), (('e', 'm'), 769), (('m', 'm'), 168), (('m', 'a'), 2590), (('a', '<E>'), 6640), (('<S>', 'o'), 394), (('o', 'l'), 619), (('l', 'i'), 2480), (('i', 'v'), 269), (('v', 'i'), 911), (('i', 'a'), 2445), (('<S>', 'a'), 4410), (('a', 'v'), 834), (('v', 'a'), 642), (('<S>', 'i'), 591), (('i', 's'), 1316), (('s', 'a'), 1201), (('a', 'b'), 541), (('b', 'e'), 655), (('e', 'l'), 3248), (('l', 'l'), 1345), (('l', 'a'), 2623), (('<S>', 's'), 2055), (('s', 'o'), 531), (('o', 'p'), 95), (('p', 'h'), 204), (('h', 'i'), 729), (('<S>', 'c'), 1542), (('c', 'h'), 664), (('h', 'a'), 2244), (('a', 'r'), 3264), (('r', 'l'), 413), (('l', 'o'), 692), (('o', 't'), 118), (('t', 't'), 374), (('t', 'e'), 716), (('e', '<E>'), 3983), (('<S>', 'm'), 2538), (('m', 'i'), 1256), (('a', 'm'), 1634), (('m', 'e'), 818), (('<S>', 'h'), 874), (('r', 'p'), 14), (('p', 'e'), 197), (('e', 'r'), 1958), (('r', '<E>'), 1377), (('e', 'v'), 463), (('v', 'e'), 568), (('l', 'y'), 1588), (('y', 'n'), 18

In [26]:
sorted(b.items(), key = lambda kv: kv[1]) # sort the dict based on count value

[(('q', 'r'), 1),
 (('d', 'z'), 1),
 (('p', 'j'), 1),
 (('q', 'l'), 1),
 (('p', 'f'), 1),
 (('q', 'e'), 1),
 (('b', 'c'), 1),
 (('c', 'd'), 1),
 (('m', 'f'), 1),
 (('p', 'n'), 1),
 (('w', 'b'), 1),
 (('p', 'c'), 1),
 (('h', 'p'), 1),
 (('f', 'h'), 1),
 (('b', 'j'), 1),
 (('f', 'g'), 1),
 (('z', 'g'), 1),
 (('c', 'p'), 1),
 (('p', 'k'), 1),
 (('p', 'm'), 1),
 (('x', 'n'), 1),
 (('s', 'q'), 1),
 (('k', 'f'), 1),
 (('m', 'k'), 1),
 (('x', 'h'), 1),
 (('g', 'f'), 1),
 (('v', 'b'), 1),
 (('j', 'p'), 1),
 (('g', 'z'), 1),
 (('v', 'd'), 1),
 (('d', 'b'), 1),
 (('v', 'h'), 1),
 (('h', 'h'), 1),
 (('g', 'v'), 1),
 (('d', 'q'), 1),
 (('x', 'b'), 1),
 (('w', 'z'), 1),
 (('h', 'q'), 1),
 (('j', 'b'), 1),
 (('x', 'm'), 1),
 (('w', 'g'), 1),
 (('t', 'b'), 1),
 (('z', 'x'), 1),
 (('p', 'b'), 2),
 (('t', 'g'), 2),
 (('q', 's'), 2),
 (('t', 'x'), 2),
 (('f', 'k'), 2),
 (('b', 't'), 2),
 (('j', 'n'), 2),
 (('k', 'c'), 2),
 (('z', 'k'), 2),
 (('s', 'j'), 2),
 (('s', 'f'), 2),
 (('z', 'j'), 2),
 (('n', 'q

In [27]:
sorted(b.items(), key = lambda kv: -kv[1]) # sort the dict based on count value; descending order

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [28]:
#now we need to keep above info into significantly convinient format insted of dictionary
#store the info into 2D format
#1st char in row & 2nd char in column
#this will tell how freq 2nd follow 1st char based on its intersection

In [29]:
import torch

In [30]:
a = torch.zeros(3, 5)

In [31]:
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [32]:
a.dtype

torch.float32

In [33]:
a = torch.zeros((3, 5), dtype=torch.int32) #as count is integer values

In [34]:
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [35]:
a[1,3] = 1 #indexing the tensors

In [36]:
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [37]:
#26 chars, 2 special chars...therefor 28 * 28 array

In [38]:
N = torch.zeros((28, 28), dtype=torch.int32)

In [39]:
char = sorted(list(set(''.join(words)))) #get all distinct char for lookup
stoi ={s:i for i,s in enumerate(char)}
stoi #notice we index characters using index

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [40]:
stoi['<S>'] = 26 #adding special chars
stoi['<E>'] = 27

In [41]:
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        N[ix1, ix2] += 1

In [42]:
N

tensor([[ 556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568, 2528,
         1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,  182,
         2050,  435,    0, 6640],
        [ 321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,  103,
            0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,    0,
           83,    0,    0,  114],
        [ 815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,  116,
            0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,    3,
          104,    4,    0,   97],
        [1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,   60,
           30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,    0,
          317,    1,    0,  516],
        [ 679,  121,  153,  384, 1271,   82,  125,  152,  818,   55,  178, 3248,
          769, 2675,  269,   83,   14, 1958,  861,  580,   69,  463,   50,  132,
         1070,  181,    0, 3983],
        [ 242,    0,

In [43]:
import matplotlib.pyplot as plt
%matplotlib inline

In [44]:
#plt.imshow(N)

In [45]:
N

tensor([[ 556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568, 2528,
         1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,  182,
         2050,  435,    0, 6640],
        [ 321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,  103,
            0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,    0,
           83,    0,    0,  114],
        [ 815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,  116,
            0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,    3,
          104,    4,    0,   97],
        [1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,   60,
           30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,    0,
          317,    1,    0,  516],
        [ 679,  121,  153,  384, 1271,   82,  125,  152,  818,   55,  178, 3248,
          769, 2675,  269,   83,   14, 1958,  861,  580,   69,  463,   50,  132,
         1070,  181,    0, 3983],
        [ 242,    0,

In [46]:
itos ={i:s for s,i in stoi.items()}

plt.figure(figsize=(16,16))
plt.imshow(N, cmap='Blues')
for i in range(28):
    for j in range(28):
        chstr = itos[i] + itos[j]
        plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
        plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
plt.axis('off');

In [47]:
#Kernal failing...

In [48]:
#noticing the graph, we identified <E> will not be a start letter for any words...hence we can optimize it

In [49]:
N = torch.zeros((27, 27), dtype=torch.int32)

In [50]:
char = sorted(list(set(''.join(words)))) #get all distinct char for lookup
stoi ={s:i+1 for i,s in enumerate(char)}
stoi['.'] = 0 #.represents special char
itos ={i:s for s,i in stoi.items()}

In [51]:
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [52]:
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        N[ix1, ix2] += 1

plt.figure(figsize=(16,16))
plt.imshow(N, cmap='Blues')
for i in range(27):
    for j in range(27):
        chstr = itos[i] + itos[j]
        plt.text(j, i, chstr, ha="center", va="bottom", color='gray')
        plt.text(j, i, N[i, j].item(), ha="center", va="top", color='gray')
plt.axis('off');

In [53]:
#N[0, :]#0th row & all column values i.e. 1D Array
#or
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [54]:
N[0, :].shape

torch.Size([27])

In [55]:
#we need to convert these values into probabilities
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [56]:
p.sum() #will be summing up to 1 since we normalized the data and converted into proba

tensor(1.)

In [57]:
#to sample these data, we use multinomial prob distribution

In [58]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()

In [59]:
p

tensor([0.6064, 0.3033, 0.0903])

In [60]:
torch.multinomial(p, num_samples=20, replacement=True, generator=g)
#60% will be 0 , 30% will be 1 & 10% will be 2...since probabilities of p is 60, 30 & 10%!!!

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [61]:
#lets do for our bag of words
#we need to convert these values into probabilities
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [62]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()

In [63]:
itos[ix]

'j'

In [64]:
g = torch.Generator().manual_seed(2147483647)

for i in range(10):
    out = []
    ix = 0
    while True:
        p = N[ix].float()
        p = p / p.sum()
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break;
    print(''.join(out))

junide.
janasah.
p.
cony.
a.
nn.
kohin.
tolian.
juee.
ksahnaauranilevias.


In [65]:
#We have generated 10 different sequence of words based on bigram probabilities
#Seems these names look terrible, because of Bigram performance
#can we fine tune  ?

In [66]:
p.shape

torch.Size([27])

In [67]:
g = torch.Generator().manual_seed(2147483647)

for i in range(10):
    out = []
    ix = 0
    while True:
        #p = N[ix].float()
        #p = p / p.sum()
        p = torch.ones(27) / 27.0 #kind of uniform distribution making everything equally likely
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break;
    print(''.join(out))

juwjdvdipkcqaz.
p.
cfqywocnzqfjiirltozcogsjgwzvudlhnpauyjbilevhajkdbduinrwibtlzsnjyievyvaftbzffvmumthyfodtumjrpfytszwjhrjagq.
coreaysezocfkyjjabdywejfmoifmwyfinwagaasnhsvfihofszxhddgosfmptpagicz.
rjpiufmthdt.
rkrrsru.
iyumuyfy.
mjekujcbkhvupwyhvpvhvccragr.
wdkhwfdztta.
mplyisbxlyhuuiqzavmpocbzthqmimvyqwat.


In [68]:
#This is something model without training...
#but bigram was something better...

In [69]:
#currently we sample one row from N and finding its probability
#instead we want to create matrix that contains all probabilities

In [70]:
P = N.float()

In [71]:
(P.sum(1, keepdim=True)) #aggregating columns at row level

tensor([[32033.],
        [33885.],
        [ 2645.],
        [ 3532.],
        [ 5496.],
        [20423.],
        [  905.],
        [ 1927.],
        [ 7616.],
        [17701.],
        [ 2900.],
        [ 5040.],
        [13958.],
        [ 6642.],
        [18327.],
        [ 7934.],
        [ 1026.],
        [  272.],
        [12700.],
        [ 8106.],
        [ 5570.],
        [ 3135.],
        [ 2573.],
        [  929.],
        [  697.],
        [ 9776.],
        [ 2398.]])

In [72]:
#P = P / (P.sum(1, keepdim=True)) #broadcasting is done here.. P is matrix, below sum is single column
P /= (P.sum(1, keepdim=True)) #much faster because of inmemory and not creating new variable

In [73]:
# 27 27
# 27 1
#Broadcasting conditions met

In [74]:
P[0].sum()

tensor(1.)

In [75]:
g = torch.Generator().manual_seed(2147483647)

for i in range(10):
    out = []
    ix = 0
    while True:
        p = P[ix]
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break;
    print(''.join(out))

junide.
janasah.
p.
cony.
a.
nn.
kohin.
tolian.
juee.
ksahnaauranilevias.


In [76]:
#getting exactly same results

In [77]:
#How quality was the above model results ?
#How to get the loss function

In [78]:
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        prob = P[ix2, ix2]
        print(f"{ch1}{ch2}: {prob:.4f}")

.e: 0.0622
em: 0.0253
mm: 0.0253
ma: 0.0164
a.: 0.0000
.o: 0.0145
ol: 0.0964
li: 0.0046
iv: 0.0027
vi: 0.0046
ia: 0.0164
a.: 0.0000
.a: 0.0164
av: 0.0027
va: 0.0164
a.: 0.0000


In [79]:
#Total 27 chars ; equaly prob = 1/27 ~ 4%
1/27

0.037037037037037035

In [80]:
#notice many bigram with above 4% which means we learned something useful from that bigram...
#if a good model, these prob should be near equal to 1
#how can we summarize these prob into a single number to arrive at loss value or that measures quality of this model?
#Maximum Likelihood Estimate function
#Product of all these probabilities and should be as high as possible
#but usually this is very very small no
#hence we go for Log Likelihood !!!

In [81]:
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        prob = P[ix2, ix2]
        logprob = torch.log(prob)
        print(f"{ch1}{ch2}: {prob:.4f} {logprob:.4f}")

.e: 0.0622 -2.7769
em: 0.0253 -3.6772
mm: 0.0253 -3.6772
ma: 0.0164 -4.1100
a.: 0.0000 -inf
.o: 0.0145 -4.2340
ol: 0.0964 -2.3397
li: 0.0046 -5.3747
iv: 0.0027 -5.9069
vi: 0.0046 -5.3747
ia: 0.0164 -4.1100
a.: 0.0000 -inf
.a: 0.0164 -4.1100
av: 0.0027 -5.9069
va: 0.0164 -4.1100
a.: 0.0000 -inf


In [82]:
#log(a*b) = log(a) + log(b)
#log will add instead of product. Hence summing of probabilities will be good no

In [83]:
log_likelihood = 0.0
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        prob = P[ix2, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        print(f"{ch1}{ch2}: {prob:.4f} {logprob:.4f}")
print(log_likelihood)

.e: 0.0622 -2.7769
em: 0.0253 -3.6772
mm: 0.0253 -3.6772
ma: 0.0164 -4.1100
a.: 0.0000 -inf
.o: 0.0145 -4.2340
ol: 0.0964 -2.3397
li: 0.0046 -5.3747
iv: 0.0027 -5.9069
vi: 0.0046 -5.3747
ia: 0.0164 -4.1100
a.: 0.0000 -inf
.a: 0.0164 -4.1100
av: 0.0027 -5.9069
va: 0.0164 -4.1100
a.: 0.0000 -inf
tensor(-inf)


In [84]:
#when all probabilities  = 1; Log(1) = 0
#when all prob are lower , log value will be more and more lower
#But definition of loss function says low is good...
#with loglikelihood, it is reverse
#hence we go for negative log likelihood

In [85]:
log_likelihood = 0.0
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        prob = P[ix2, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        print(f"{ch1}{ch2}: {prob:.4f} {logprob:.4f}")

print(f'Log Likelihood = {log_likelihood}')
nll = -log_likelihood
print(f'Negative Log Likelihood = {nll}')

.e: 0.0622 -2.7769
em: 0.0253 -3.6772
mm: 0.0253 -3.6772
ma: 0.0164 -4.1100
a.: 0.0000 -inf
.o: 0.0145 -4.2340
ol: 0.0964 -2.3397
li: 0.0046 -5.3747
iv: 0.0027 -5.9069
vi: 0.0046 -5.3747
ia: 0.0164 -4.1100
a.: 0.0000 -inf
.a: 0.0164 -4.1100
av: 0.0027 -5.9069
va: 0.0164 -4.1100
a.: 0.0000 -inf
Log Likelihood = -inf
Negative Log Likelihood = inf


In [86]:
#normalize the loss function
log_likelihood = 0.0
n = 0
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        prob = P[ix2, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f"{ch1}{ch2}: {prob:.4f} {logprob:.4f}")

print(f'Log Likelihood = {log_likelihood}')
nll = -log_likelihood
print(f'Negative Log Likelihood = {nll}')
print(f'Avg neg log likelihood = {nll/n}')

.e: 0.0622 -2.7769
em: 0.0253 -3.6772
mm: 0.0253 -3.6772
ma: 0.0164 -4.1100
a.: 0.0000 -inf
.o: 0.0145 -4.2340
ol: 0.0964 -2.3397
li: 0.0046 -5.3747
iv: 0.0027 -5.9069
vi: 0.0046 -5.3747
ia: 0.0164 -4.1100
a.: 0.0000 -inf
.a: 0.0164 -4.1100
av: 0.0027 -5.9069
va: 0.0164 -4.1100
a.: 0.0000 -inf
Log Likelihood = -inf
Negative Log Likelihood = inf
Avg neg log likelihood = inf


In [87]:
#Goal is to maximize likelihood of the data w.r.t model parameters
#equivalent to maximise the log likelihood function
#equivalent to maximize the negative log likelihood function

In [88]:
#normalize the loss function
log_likelihood = 0.0
n = 0
for w in ["andre"]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        prob = P[ix2, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f"{ch1}{ch2}: {prob:.4f} {logprob:.4f}")

print(f'Log Likelihood = {log_likelihood}')
nll = -log_likelihood
print(f'Negative Log Likelihood = {nll}')
print(f'Avg neg log likelihood = {nll/n}')

.a: 0.0164 -4.1100
an: 0.1040 -2.2634
nd: 0.0271 -3.6078
dr: 0.0335 -3.3973
re: 0.0622 -2.7769
e.: 0.0000 -inf
Log Likelihood = -inf
Negative Log Likelihood = inf
Avg neg log likelihood = inf


In [89]:
#normalize the loss function
log_likelihood = 0.0
n = 0
for w in ["balajij"]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        prob = P[ix2, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f"{ch1}{ch2}: {prob:.4f} {logprob:.4f}")

print(f'Log Likelihood = {log_likelihood}')
nll = -log_likelihood
print(f'Negative Log Likelihood = {nll}')
print(f'Avg neg log likelihood = {nll/n}')

.b: 0.0144 -4.2428
ba: 0.0164 -4.1100
al: 0.0964 -2.3397
la: 0.0164 -4.1100
aj: 0.0007 -7.2793
ji: 0.0046 -5.3747
ij: 0.0007 -7.2793
j.: 0.0000 -inf
Log Likelihood = -inf
Negative Log Likelihood = inf
Avg neg log likelihood = inf


In [90]:
#log likelihood is going to infinity ???
#because j. combination is not available in bigram model..hence prob goes to infinity
#to avoid this, need to smooth out the model
#we add 1 to values instead of 0

In [91]:
P = (N+1).float() #this will ensure no prob with 0

In [92]:
P /= P.sum(1, keepdims=True)

In [93]:
g = torch.Generator().manual_seed(2147483647)

for i in range(10):
    out = []
    ix = 0
    while True:
        p = P[ix]
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break;
    print(''.join(out))

junide.
janasah.
p.
cony.
a.
nn.
kohin.
tolian.
juee.
ksahnaauranilevias.


In [94]:
#normalize the loss function
log_likelihood = 0.0
n = 0
for w in ["balajij"]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1] #get the index of character1
        ix2 = stoi[ch2] #get the index of character2
        prob = P[ix2, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f"{ch1}{ch2}: {prob:.4f} {logprob:.4f}")

print(f'Log Likelihood = {log_likelihood}')
nll = -log_likelihood
print(f'Negative Log Likelihood = {nll}')
print(f'Avg neg log likelihood = {nll/n}')

.b: 0.0146 -4.2270
ba: 0.0164 -4.1090
al: 0.0962 -2.3408
la: 0.0164 -4.1090
aj: 0.0010 -6.8831
ji: 0.0047 -5.3641
ij: 0.0010 -6.8831
j.: 0.0000 -10.3754
Log Likelihood = -44.29145050048828
Negative Log Likelihood = 44.29145050048828
Avg neg log likelihood = 5.536431312561035


In [95]:
#So now, our model will predict some loss values instead of infinity

In [96]:
#Till now, we trained a respectable Bigram Model
#we created list of bigrams, its co-occurance count
#converted into probabilities & normalized
#and sample character to generate new words
#and found loss function to measure performance of model

In [97]:
#Lets implement the same using pytorch

In [98]:
import torch

In [99]:
#create the training set of all the bigrams (x, y)

In [100]:
xs, ys = [], []
for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)# instead we add input into xs
        ys.append(ix2)# equivalent next char output into ys

xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .


In [101]:
xs

tensor([ 0,  5, 13, 13,  1])

In [102]:
ys

tensor([ 5, 13, 13,  1,  0])

In [103]:
#will create 1 - hot encoding

In [104]:
import torch.nn.functional as F

In [105]:
xenc = F.one_hot(xs, 27) # input, no of classes

In [106]:
xenc.shape

torch.Size([5, 27])

In [107]:
#plt.imshow(xenc)

In [109]:
xenc #notice how encoding is done

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]])

In [110]:
xenc.dtype

torch.int64

In [114]:
xenc = xenc.float()

In [116]:
xenc.dtype#since tensor operate using float

torch.float32

In [118]:
W = torch.randn((27, 1))
W

tensor([[ 1.6009],
        [ 0.4836],
        [ 0.1940],
        [ 1.9925],
        [ 0.5382],
        [-0.4097],
        [ 0.0469],
        [ 1.6689],
        [ 0.6652],
        [-0.2756],
        [ 0.2623],
        [-1.0403],
        [-0.5606],
        [-1.2323],
        [-0.2055],
        [ 1.1763],
        [ 0.0605],
        [-0.7068],
        [-1.4584],
        [-0.1220],
        [ 0.1921],
        [-0.5486],
        [ 0.0241],
        [-1.9292],
        [ 0.8182],
        [ 1.4553],
        [ 0.2873]])

In [119]:
xenc @ W #@ refers matrix multiplication

tensor([[ 1.6009],
        [-0.4097],
        [-1.2323],
        [-1.2323],
        [ 0.4836]])

In [ ]:
# (5, 27) @ (27, 1) = (5, 1)
#because 27 will multiply & add

In [120]:
W = torch.randn((27, 27))
W

tensor([[-1.4127e+00, -1.0323e+00, -1.2416e+00, -1.3529e+00, -3.7065e-01,
         -2.0843e+00,  4.8626e-01, -2.0800e-01,  2.0811e-01, -7.2852e-01,
          3.1693e-04, -3.7791e-01,  3.5539e-02, -7.8472e-01, -1.7430e+00,
         -2.1291e-01,  1.5303e+00,  3.2433e-01, -2.2134e-01,  1.9307e+00,
          1.0623e-01,  4.0056e-01,  1.6609e+00,  1.4033e-01, -9.6486e-01,
          8.6772e-02,  1.4405e+00],
        [-4.0569e-01,  1.3693e+00,  1.3742e-01, -4.8969e-01,  1.5117e+00,
          6.1550e-01, -4.2795e-01, -5.7637e-01,  6.9940e-01,  2.9226e-01,
         -1.4475e+00, -2.6385e-01, -1.3356e+00,  1.1788e+00,  1.2694e+00,
          1.2456e+00,  2.0707e+00, -7.2070e-01, -1.6873e+00, -1.0932e+00,
          1.5943e+00,  2.2989e-01, -1.5005e+00, -5.6755e-01,  3.3543e-01,
          1.7593e+00, -9.6089e-01],
        [ 4.8009e-01,  2.3811e+00,  1.0540e+00,  7.2272e-01, -1.4951e+00,
          7.2220e-01,  2.6590e-01,  1.8818e-01, -7.5627e-01, -1.0150e+00,
          1.5757e+00,  8.3883e-02,  2.84

In [121]:
xenc @ W

tensor([[-1.4127e+00, -1.0323e+00, -1.2416e+00, -1.3529e+00, -3.7065e-01,
         -2.0843e+00,  4.8626e-01, -2.0800e-01,  2.0811e-01, -7.2852e-01,
          3.1693e-04, -3.7791e-01,  3.5539e-02, -7.8472e-01, -1.7430e+00,
         -2.1291e-01,  1.5303e+00,  3.2433e-01, -2.2134e-01,  1.9307e+00,
          1.0623e-01,  4.0056e-01,  1.6609e+00,  1.4033e-01, -9.6486e-01,
          8.6772e-02,  1.4405e+00],
        [ 2.1297e+00, -1.4128e+00,  1.4160e+00,  1.2280e+00,  3.7320e-01,
          1.4479e+00, -1.3197e+00,  4.3890e-01, -3.5884e-01, -8.8091e-02,
         -7.5033e-01,  7.0202e-01, -9.0377e-01,  7.6061e-01,  2.1112e+00,
         -2.0073e+00, -5.8846e-01,  1.3949e-01, -8.6333e-02,  4.7706e-01,
         -1.1149e+00,  4.1814e-01,  4.8450e-01,  6.1192e-01, -9.1331e-01,
         -5.2665e-01,  2.2808e-01],
        [-1.0154e+00,  1.1600e-01, -3.0322e-01, -9.9661e-01, -1.6538e+00,
         -1.5214e+00, -6.4469e-01,  5.3138e-01,  2.8008e-01,  8.4764e-01,
          1.4783e+00, -5.5993e-01, -3.48

In [124]:
# (5, 27) @ (27, 27) = (5, 27)
(xenc @ W).shape

torch.Size([5, 27])

In [126]:
#What is every element in output matrxi (5, 27) telling us?
#for every one of 27 neurons that created , what is the firing rate of those neurons on 5 inputs given
(xenc @ W)[3, 13]
#firing rate of 13 neuron looking at the 3rd input; we achieved by dot pdt between 3rd input & 13th column of W matrix

tensor(0.2738)

In [127]:
xenc[3]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [131]:
W[:, 13]

tensor([-0.7847,  1.1788, -1.4964, -0.7272,  0.2562,  0.7606,  1.5276, -1.9202,
        -1.7109,  0.2005, -1.1069, -0.8282, -0.3656,  0.2738,  1.2501,  0.1364,
        -0.0061,  0.4221, -0.3988,  0.4151, -1.5301,  1.1647,  0.8644,  1.2940,
         0.8361,  0.7953,  0.5051])

In [129]:
(xenc[3] * W[:, 13]).sum()

tensor(0.2738)

In [132]:
#notice the output is same as above
#matrix multiplication is more efficient than doing individually

In [133]:
#till now we did only x*W ; not added bias & non-linearity function
#Lets interprest these 27 neuron values !!!
#Notice these no's are both +ve & -ve values...coming from randn function

In [134]:
#But what we want ?
#Previously in Bigram, we have a matrix for each co-occurance of characters, we counted the freq of co-occurance
#we Normalized the counts to get probabilities and wanted to have similar in pytorch model
#count are usually +ve and sum to 1 & prob is always between 0 to 1
#these prob represents the prob of next char given a char...
#currently in pytorch, neuron matrix is some +ve & -ve no's


In [138]:
#in pytorch matrix, these 27 no's are basically log counts
#to get counts, we take log & exp
logits = (xenc @ W) #we will consider as log-counts
counts = logits.exp() #this will give positive no and interpret as freq of each co-occurance. this is equivalent to N Matrix
#notice all becomes +ve because of exponential function
probs = counts/counts.sum(1, keepdims=True) # normalize the rows to get probabilities
probs
#softmax function - taking logits and exponetiate and divide by total

tensor([[0.0063, 0.0092, 0.0075, 0.0067, 0.0178, 0.0032, 0.0420, 0.0210, 0.0318,
         0.0125, 0.0259, 0.0177, 0.0268, 0.0118, 0.0045, 0.0209, 0.1194, 0.0358,
         0.0207, 0.1782, 0.0287, 0.0386, 0.1361, 0.0297, 0.0098, 0.0282, 0.1092],
        [0.1664, 0.0048, 0.0815, 0.0675, 0.0287, 0.0842, 0.0053, 0.0307, 0.0138,
         0.0181, 0.0093, 0.0399, 0.0080, 0.0423, 0.1634, 0.0027, 0.0110, 0.0227,
         0.0181, 0.0319, 0.0065, 0.0301, 0.0321, 0.0365, 0.0079, 0.0117, 0.0248],
        [0.0088, 0.0274, 0.0180, 0.0090, 0.0047, 0.0053, 0.0128, 0.0415, 0.0323,
         0.0569, 0.1069, 0.0139, 0.0172, 0.0321, 0.0229, 0.0113, 0.1109, 0.0412,
         0.0563, 0.0541, 0.0701, 0.0131, 0.0337, 0.0337, 0.0129, 0.1127, 0.0403],
        [0.0088, 0.0274, 0.0180, 0.0090, 0.0047, 0.0053, 0.0128, 0.0415, 0.0323,
         0.0569, 0.1069, 0.0139, 0.0172, 0.0321, 0.0229, 0.0113, 0.1109, 0.0412,
         0.0563, 0.0541, 0.0701, 0.0131, 0.0337, 0.0337, 0.0129, 0.1127, 0.0403],
        [0.0127, 0.0751,

In [139]:
probs[0].sum()

tensor(1.0000)

In [140]:
#notice all rows count will sum to 1

In [141]:
probs.shape

torch.Size([5, 27])

In [142]:
probs[0]
#1. basically we feeded "." into neural net using 1-hot encoder
#2. Post transformations, we got below weights prob
#3. we will tune this W - prob using backprop to predict next char

tensor([0.0063, 0.0092, 0.0075, 0.0067, 0.0178, 0.0032, 0.0420, 0.0210, 0.0318,
        0.0125, 0.0259, 0.0177, 0.0268, 0.0118, 0.0045, 0.0209, 0.1194, 0.0358,
        0.0207, 0.1782, 0.0287, 0.0386, 0.1361, 0.0297, 0.0098, 0.0282, 0.1092])

In [143]:
#summary---------------------------------------------------

In [144]:
xs

tensor([ 0,  5, 13, 13,  1])

In [145]:
ys

tensor([ 5, 13, 13,  1,  0])

In [167]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27), generator=g)

In [168]:
#forward pass
#xenc , logits, counts, prob all differentiable, hence we can back propagate
xenc = F.one_hot(xs, num_classes=27).float()#input to the network using one hot encoder
logits = xenc @ W #predict log counts
counts = logits.exp() # counts, equivelant to N
probs = counts/counts.sum(1, keepdims=True) #prob of next character
#between: last 2 lines here are together called a softmax

In [169]:
probs.shape

torch.Size([5, 27])

In [170]:
#taking 5 examples
nlls = torch.zeros(5)
for i in range(5):
    x = xs[i].item() #input character index
    y = ys[i].item() #label character index
    print('--------------------')
    print(f'bigram example {i+1}: {itos[x]}{itos[y]} (indexes {x},{y})')
    print('input to the neural net: ', x)
    print('output probabilities from the neural net: ', probs[i])
    print('label  (actual next character):', y)
    p = probs[i, y]
    print('probablity assigned by the net to the correct chracter:', p.item())
    logp = torch.log(p)
    print('log likelihood:', logp.item())
    nll = -logp
    print('negative log likelihood:', nll.item())
    nlls[i] = nll

print('============')
print('average negative log likelihhood i.e. loss=', nlls.mean().item())

--------------------
bigram example 1: .e (indexes 0,5)
input to the neural net:  0
output probabilities from the neural net:  tensor([0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
        0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
        0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459])
label  (actual next character): 5
probablity assigned by the net to the correct chracter: 0.01228625513613224
log likelihood: -4.399273872375488
negative log likelihood: 4.399273872375488
--------------------
bigram example 2: em (indexes 5,13)
input to the neural net:  5
output probabilities from the neural net:  tensor([0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
        0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
        0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472])
label  (actual next character): 13
probablity assigned by the net to the co

In [171]:
#by changing seed...we seee different avg loss value

In [172]:
#we can minimize loss by tuning W using gradient based optimization

In [173]:
#Optimization--------------------------------!!!

In [208]:
xs

tensor([ 0,  5, 13, 13,  1])

In [209]:
ys

tensor([ 5, 13, 13,  1,  0])

In [210]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27), generator=g, requires_grad = True)#tell pytorch for gradients to backpropagate

In [211]:
xenc = F.one_hot(xs, num_classes=27).float()#input to the network using one hot encoder
logits = xenc @ W #predict log counts
counts = logits.exp() # counts, equivelant to N
probs = counts/counts.sum(1, keepdims=True) #prob of next character

In [212]:
#refer from our Micrograd project, lets calculate loss and backpropate the gradients and update W parameters

In [213]:
probs.shape

torch.Size([5, 27])

In [214]:
probs[0, 5], probs[1, 13], probs[2, 13], probs[3, 1], probs[4, 0]

(tensor(0.0123, grad_fn=<SelectBackward0>),
 tensor(0.0181, grad_fn=<SelectBackward0>),
 tensor(0.0267, grad_fn=<SelectBackward0>),
 tensor(0.0737, grad_fn=<SelectBackward0>),
 tensor(0.0150, grad_fn=<SelectBackward0>))

In [215]:
#insted of manual picking, how to pass it dynamically?

In [216]:
import numpy as np

In [217]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [218]:
probs[torch.arange(5), ys]

tensor([0.0123, 0.0181, 0.0267, 0.0737, 0.0150], grad_fn=<IndexBackward0>)

In [219]:
loss = -probs[torch.arange(5), ys].log().mean() #negative log likeklihood averange loss 

In [220]:
loss

tensor(3.7693, grad_fn=<NegBackward0>)

In [221]:
#now we are ready for backpass

In [222]:
#first set all gradients to 0
W.grad = None
loss.backward()

In [223]:
#backwards fill all the gradients

In [224]:
W.grad

tensor([[ 0.0121,  0.0020,  0.0025,  0.0008,  0.0034, -0.1975,  0.0005,  0.0046,
          0.0027,  0.0063,  0.0016,  0.0056,  0.0018,  0.0016,  0.0100,  0.0476,
          0.0121,  0.0005,  0.0050,  0.0011,  0.0068,  0.0022,  0.0006,  0.0040,
          0.0024,  0.0307,  0.0292],
        [-0.1970,  0.0017,  0.0079,  0.0020,  0.0121,  0.0062,  0.0217,  0.0026,
          0.0025,  0.0010,  0.0205,  0.0017,  0.0198,  0.0022,  0.0046,  0.0041,
          0.0082,  0.0016,  0.0180,  0.0106,  0.0093,  0.0062,  0.0010,  0.0066,
          0.0131,  0.0101,  0.0018],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000

In [225]:
#updating weights based on gradients
W.data += -0.1 * W.grad

In [226]:
#since we updated weights, loss should decrease
#re running forward pass
xenc = F.one_hot(xs, num_classes=27).float()#input to the network using one hot encoder
logits = xenc @ W #predict log counts
counts = logits.exp() # counts, equivelant to N
probs = counts/counts.sum(1, keepdims=True) #prob of next character
loss = -probs[torch.arange(5), ys].log().mean() #negative log likeklihood averange loss 
print(loss.item())

3.7492127418518066


In [228]:
#3.76 to 3.74 yay, loss reduced
#keep running, notice reduction in loss value

In [229]:
#Putting it all together

In [240]:
#create the dataset
xs, ys = [], []
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of exmaple: ', num)

#initialize the network
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27), generator=g, requires_grad = True)

number of exmaple:  228146


In [242]:
#gradient descent
for k in range(100):
    #forward pass
    xenc = F.one_hot(xs, num_classes=27).float()
    logits = xenc @ W
    counts = logits.exp()
    probs = counts/ counts.sum(1, keepdims=True)
    loss = -probs[torch.arange(num), ys].log().mean()
    print(loss.item())
    
    #backward pass
    W.grad = None
    loss.backward()
    
    #update weights
    W.data += -50 * W.grad

2.4726529121398926
2.4724340438842773
2.4722201824188232
2.472010850906372
2.4718058109283447
2.4716053009033203
2.471409320831299
2.471216917037964
2.4710283279418945
2.470843553543091
2.4706625938415527
2.4704854488372803
2.4703118801116943
2.4701414108276367
2.4699742794036865
2.4698104858398438
2.4696500301361084
2.469492197036743
2.4693377017974854
2.4691858291625977
2.4690372943878174
2.468891143798828
2.468747615814209
2.46860671043396
2.468468427658081
2.468332529067993
2.4681990146636963
2.4680681228637695
2.4679393768310547
2.4678127765655518
2.46768856048584
2.4675662517547607
2.4674463272094727
2.467327833175659
2.467211961746216
2.467097759246826
2.4669857025146484
2.4668753147125244
2.466766357421875
2.4666597843170166
2.466554641723633
2.4664509296417236
2.4663491249084473
2.4662492275238037
2.4661505222320557
2.4660532474517822
2.4659576416015625
2.4658634662628174
2.4657704830169678
2.465679407119751
2.4655895233154297
2.465500593185425
2.4654135704040527
2.46532750129

In [243]:
#notice the loss function saturates around 2.4 which more or less similar results from our basic neural nets
#This is because our pytorch nerual net is very simple
# we have 1 input layer and its weight to predict output
#this is scalable approach

In [245]:
# 2 important things to be noted

# 1) xenc * W where xenc is 1 hot encode multiplied with weights. 1 hot encoder actually pick the respective row based on 1
# and multiply. rows represents current char and we need to find the respective next char prob from that row only. 
#W is log counts. 

# 2) note the smoothing we added in previous network  "P = (N+1).float()"? this will smooth out the distribution of
#probabilities, which will prevent of assigning any 0 probabilities for a bigram. More and more increase of count
#prob will become more uniform. Similary we are doing in Gradient based approach!!!

#If all weight in W is 0. but we take exp which will make exp(0) = 1 

#this is called as regularization

#basically we are augmenting the loss function to have small component called as "Regularization Loss"

In [247]:
for k in range(100):
    #forward pass
    xenc = F.one_hot(xs, num_classes=27).float()
    logits = xenc @ W
    counts = logits.exp()
    probs = counts/ counts.sum(1, keepdims=True)
    loss = -probs[torch.arange(num), ys].log().mean() + (0.01*(W**2).mean()) #adding regularization loss
    print(loss.item())
    
    #backward pass
    W.grad = None
    loss.backward()
    
    #update weights
    W.data += -50 * W.grad

2.4834256172180176
2.4833858013153076
2.4833483695983887
2.4833130836486816
2.4832799434661865
2.4832475185394287
2.4832167625427246
2.483186960220337
2.4831581115722656
2.4831299781799316
2.483102798461914
2.483076333999634
2.48305082321167
2.4830257892608643
2.483001232147217
2.4829773902893066
2.482954263687134
2.48293137550354
2.4829089641571045
2.4828872680664062
2.482866048812866
2.4828453063964844
2.4828240871429443
2.482804298400879
2.4827845096588135
2.482764959335327
2.48274564743042
2.482727289199829
2.48270845413208
2.4826903343200684
2.4826724529266357
2.4826548099517822
2.482637643814087
2.4826207160949707
2.4826037883758545
2.4825873374938965
2.4825706481933594
2.4825544357299805
2.482538938522339
2.482523202896118
2.4825077056884766
2.482492446899414
2.4824774265289307
2.4824624061584473
2.482448101043701
2.482433557510376
2.48241925239563
2.4824047088623047
2.482390880584717
2.482377290725708
2.48236346244812
2.4823503494262695
2.4823367595672607
2.48232364654541
2.482

In [ ]:
#now optimization has 2 components; Loss function not only all the probabilities to work out but in addtion to that
#simultaneously tries to make all w's to 0.

In [249]:
#Finally generating sequence from the neural net model

g = torch.Generator().manual_seed(2147483647)

for i in range(5):
    out = []
    ix = 0
    while True:
        
        p = P[ix]
        #---------------------
        #xenc = F.one_hot(torch.tensor[ix], num_classes=27).float()
        #logits = xenc @ W
        #counts = logits.exp()
        #p = counts / counts.sum(1, keepdims=True) #p comes from neural net
        #----------------
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))

junide.
janasah.
p.
cony.
a.


In [251]:
#Finally generating sequence from the neural net model

g = torch.Generator().manual_seed(2147483647)

for i in range(5):
    out = []
    ix = 0
    while True:
        #------befor p is coing from ix---------
        #p = P[ix]
        #---------------------
        #Now
        xenc = F.one_hot(torch.tensor([ix]), num_classes=27).float()
        logits = xenc @ W
        counts = logits.exp()
        p = counts / counts.sum(1, keepdims=True) #p comes from neural net
        #----------------
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))

junide.
janasah.
prelay.
a.
nn.


In [252]:
###??much better output ???